server:
  port: 8080

spring:
  ai:
    openai:
      api-key: BCDWBL83ujkj4wj23bYqAFgSqf3YhrREHrqvGi9dF1z5Tas86QnyJQQJ99BEACYeBjFXJ3w3AAABACOGFUfV
      endpoint: https://fdxopenai.openai.azure.com/
      deployment: gpt-4o
      deployment-id: gpt-4o
      model: gpt-4o
      api-version: 2024-12-01-preview
      chat:
        stream: false