server:
  port: 8080

spring:
  ai:
    openai:
      api-key: YOUR-API-KEY
      endpoint: https://fdxopenai.openai.azure.com/
      deployment: gpt-4o
      deployment-id: gpt-4o
      model: gpt-4o
      api-version: 2024-12-01-preview
      chat:
        stream: false
